name: Draft Release
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:

  draft-release:
    uses: skyworksinc/.github/.github/workflows/draft-release.yml@main
    with:
      package: package_name
