
name: Release Documentation

on:
  workflow_call:
    inputs:
      docs-path:
        description: "Path where the docs will be released"
        required: true
        type: string

jobs:
  release:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - run: mkdir -p ${{ runner.temp }}/release_artifacts
      - name: release-downloader
        uses: robinraju/release-downloader@v1.2
        with:
          repository: ${{ github.repository }}
          out-file-path: ${{ runner.temp }}/release_artifacts
          tarBall: false
          zipBall: false
          token: ${{ github.token }}
          fileName: "documentation.zip"
          latest: true
      - name: Display structure of downloaded files
        run: |
          ls -R
        working-directory: ${{ runner.temp }}/release_artifacts
      - name: Release docs to production
        run: |
          mkdir -p html
          unzip -o ./documentation.zip -d html
          ls -R
          rsync -avzl html/* ${{ inputs.docs-path }}
          echo "Documentation released to ${{ inputs.docs-path }}"
        working-directory: ${{ runner.temp }}/release_artifacts
