name: Release Env
# Updates a production environment with the specified definition yaml file
#  The environment is created if it doesn't exist yet.
# It also adds the environments yml file in the root envs folder.
on:
  workflow_call:
    inputs:
      env-yaml-path:
        required: true
        type: string
      env-name:
        required: false
        type: string
        default: ''
      env-prefix:
        required: false
        type: string
        default: ''
      
env:
  RELEASE_CHANNEL: "/prj/ids/ids-conda/channels/ids-skyworks"
  IDS_ENVS_ROOT: "/prj/ids/ids-conda/envs-production"

jobs:
  update-env:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: update env
        run: |
          cp -f ${{ inputs.env-yaml-path }} ${{ env.IDS_ENVS_ROOT }}/
          source ${{ env.IDS_ENVS_ROOT }}/base/etc/profile.d/conda.sh
          if [ ! -z ${{ inputs.env-name }} ]; then
            echo "updating ${{ inputs.env-name }}"
            conda env update -y -n ${{ inputs.env-name }} \
                             -f ${{ inputs.env-yaml-path }} \
            || \
            conda env create -y -n ${{ inputs.env-name }} \
                             -f ${{ inputs.env-yaml-path }} || \
          elif [ ! -z ${{ inputs.env-prefix }} ]; then
            echo "updating ${{ inputs.env-prefix }}"
            conda env update -y -p ${{ inputs.env-prefix }} \
                             -f ${{ inputs.env-yaml-path }}
            || \
            conda env create -y -p ${{ inputs.env-prefix }} \
                             -f ${{ inputs.env-yaml-path }}
          else
            echo "Env update skipped since neither"
            echo "env-name nor env-prefix was specified"
          fi
