
name: Production Release Conda Packages

on:
  workflow_call:
env:
  RELEASE_CHANNEL: "/prj/ids/ids-conda/channels/ids-skyworks"

jobs:
  release:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - run: mkdir -p ${{ runner.temp }}/release_artifacts
      - name: Download Packages
        uses: robinraju/release-downloader@v1.2
        with:
          repository: ${{ github.repository }}
          out-file-path: ${{ runner.temp }}/release_artifacts
          tarBall: false
          zipBall: false
          token: ${{ github.token }}
          fileName: 'conda_package.zip'
          latest: true
      - name: Display structure of downloaded files
        run: |
          unzip 'conda_package.zip'
          ls -Ral
        working-directory: ${{ runner.temp }}/release_artifacts
      - name: release conda package
        run: |
          source /prj/ids/ids-conda/envs/anaconda/etc/profile.d/conda.sh
          conda activate build
          echo "RELEASING TO PROD CHANNEL"
          echo "-------------------------"
          find . -name "*.tar.bz2" -exec cp '{}' ${{ env.RELEASE_CHANNEL }}/linux-64/ \;
          ls -al ${{ env.RELEASE_CHANNEL }}/linux-64/
          echo "Indexing IDS CHANNEL"
          echo "--------------------"
          conda index ${{ env.RELEASE_CHANNEL }}
          echo "Conda packages released to ${{ env.RELEASE_CHANNEL }}"
        working-directory: ${{ runner.temp }}/release_artifacts
