
name: Test Release workflows

on:
  workflow_dispatch:

jobs:
  test-draft-release:
    uses: skyworksinc/.github/.github/workflows/draft-release.yml@main
    
  test-release-docs:
    uses: skyworksinc/.github/.github/workflows/release-docs.yml@main
    needs: test-draft-release
    with: 
      docs-path: "/prj/ids/docs/example"

  test-release-pkg:
      uses: skyworksinc/.github/.github/workflows/release-pkg.yml@main
      needs: test-draft-release
  
  test-update-env:
      uses: skyworksinc/.github/.github/workflows/update-env.yml@main
      needs: test-release-pkg
