
name: Update Env Package

on:
  workflow_call:
    inputs:
      env:
        description: 'The environment''s name'
        required: true
        type: string
      package-name:
        required: true
        type: string
env:
  BASE_ENV_PREFIX: "/prj/ids/ids-conda/envs-production/base"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  update-env-package:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: update env
        run: |
          echo "updating ${{ inputs.env }}"
          source ${{ env.BASE_ENV_PREFIX }}/etc/profile.d/conda.sh
          conda activate ${{ inputs.env }} && \
          conda update -y ${{ inputs.package-name }} || \
            conda install -y ${{ inputs.package-name }} || \
          conda create -y ${{ inputs.env }} && \
            conda install -y ${{ inputs.package-name }}
